# Generated by Django 2.2 on 2020-07-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locatin',
            new_name='location',
        ),
    ]
